config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'welcome', to: 'static_pages#welcome'
  get 'meidaisai', to: 'static_pages#meidaisai'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :members
  resources :skills
  resources :sns_links
  resources :products
  resources :product_links
  resources :member_products
  resources :entries
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :member
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  before_save { email.downcase! }

  has_many :skills, dependent: :destroy
  has_many :sns_links, dependent: :destroy
  has_many :member_products, dependent: :destroy
  has_many :products, through: :member_products
  has_many :entries
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :university, presence: true
  validates :password, presence: true, allow_nil: true

  def grade
    enroll = self.enroll
    today = Date.today
    grade = 0
    loop {
      grade += 1
      enroll = enroll.next_year
      if today<enroll
        break;
      end
    }
    grade -= self.repeat
    if grade < 1 then grade = 1 end
    if  (grade > 2 && university.match(/大学院/)) ||
        (grade > 4 && university.match(/大学/) && !university.match(/医学科/)) ||
        (grade > 6 && university.match(/大学/) && university.match(/医学科/)) ||
        (grade > 2 && university.match(/短期大学/))
      "卒業"
    else
      "#{(grade)}年"
    end
  end
end

app/models/member_product.rb
class MemberProduct < ApplicationRecord
  belongs_to :member
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  serialize :screenshots
  has_many :members, through: :member_products
  has_many :member_products, dependent: :destroy
  has_many :product_links
  accepts_nested_attributes_for :member_products
end

app/models/product_link.rb
class ProductLink < ApplicationRecord
  belongs_to :product
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :member
end

app/models/sns_link.rb
class SnsLink < ApplicationRecord
  belongs_to :member
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :genre, :place, :describe, :start_at, :end_at)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :require_login
  before_action :set_skill, only: [:edit, :update, :destroy]
  def new
    @skill = Skill.new
  end

  def create
    if current_member.skills.create(skill_param)
      redirect_to member_path(current_member.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @skill.update_attributes(skill_param)
      redirect_to member_path(current_member.id)
    else
      render :new
    end
  end

  def destroy
    @skill.destroy
    redirect_to member_path(current_member.id)
  end

  private
  def set_skill
    @skill = Skill.find_by(id: params[:id])
  end
  def skill_param
    params.require(:skill).permit(:name, :start_at)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def welcome
  end

  def meidaisai
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    if page_title.empty?
      "jack - アプリ製作団体"
    else
      "#{page_title} | jack - アプリ製作団体"
    end
  end
  def distance_of_time_in_words(from_time, to_time)
    from_time = from_time.to_date if from_time.respond_to?(:to_date)
    to_time = to_time.to_date if to_time.respond_to?(:to_date)
    years = 0
    months = 0
    loop {
      from = from_time + years.year + months.month
      if    (to_time - (from + 1.year))  >= 0 then years  += 1
      elsif (to_time - (from + 1.month)) >= 0 then months += 1
      else break
      end
    }
    distance = ''
    distance += "#{years}年" if years != 0
    distance += "#{months}ヶ月"
    distance
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def gravatar_for(user, options = {size: 100, class:''})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: options[:class])
  end
end

app/helpers/product_links_helper.rb
module ProductLinksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(member)
    session[:member_id] = member.id
  end

  def login?
    !!current_member
  end

  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end

  def member_auth?(member_id)
    login? && current_member.id.to_i == member_id.to_i
  end

  def logout
    session.delete(:member_id)
    @current_member = nil
  end

  def require_login
    until login?
      redirect_to root_path and return
    end
  end
  def require_auth
    until member_auth?(params[:id])
      redirect_to root_path and return
    end
  end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/sns_links_helper.rb
module SnsLinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:page_title, "jackとは") %>
<div class="page-header" title="about"></div>
<div class="container">
  <div class="padding"></div>
  <h2 class="english-shadow" title="information">サークル・団体情報</h2>
  <table class="table table-2col">
    <tr>
      <th>サークル・団体名</th>
      <td>jack</td>
    </tr>
    <tr>
      <th>設立年月日</th>
      <td>2015年11月3日</td>
    </tr>
    <tr>
      <th>人数</th>
      <td><%= Member.count %>人</td>
    </tr>
    <tr>
      <th>活動場所</th>
      <td>名古屋大学</td>
    </tr>
    <tr>
      <th>活動内容</th>
      <td>
        <ul>
          <li>Android・iOSアプリケーション製作</li>
          <li>パソコン用ソフトウェア製作</li>
          <li>サービス・ゲーム企画の構想および運営</li>
          <li>Webコンテンツ製作・提供</li>
          <li>各種ハッカソン・ITイベントへの参加 等</li>
        </ul>
      </td>
    </tr>
  </table>
  <div class="padding"></div>
  <h2 class="english-shadow" title="group identity">サークル・団体理念</h2>
  <h5>やりたいことをやろう</h5>
  <p>
    人は漠然としていても何かしらやりたいことがあると思う。日々の生活や社会に流されてしまい、自分の中にある本当にやりたいことができていないことが多い。jackのメンバー自身がやりたいことをするとともに、他の人もそうなってもらいたい。
  </p>
  <h5>やるからにはちゃんとやろう</h5>
  <p>
    ”ちゃんと”には次の意味合いがあると思っている。
    『中途半端にやらず、０から初めて１００までやる』
    『人に受け入れられる必要なことをする』
    『過程を楽しみ、結果を求める』『自分の今後をつくることをする』
    やりたいことがあっても中々やりきることは難しい。理想的な状態に到達するまでには長い道のりがある。道中が険しい山があるかもしれない。でも、人から求められることであればどうだろうか？過程が楽しければどうだろうか？jackは過程を楽しみ、人のためになることをしよう。
    しかし、なおも思い悩む、自分の上っている山の先に未来はあるのだろうか？、登りきったら次は何があるのだろうか？jackはメンバーの今後につながる経験を積む場であるべきだ。今後の自分のためになることを行って行くとともに、どこに行っても必要となる経験も積んでいこう。
  </p>
  <h5>ITを足掛かりに、「want」を達成する</h5>
  <p>
    jackはアプリやWebコンテンツをつくっている。それには、企画・開発・運営といったことが必要だ。ITは自分たちがやりたいことを達成するための強力な手段である。一方、プログラムを書くことが全てではない。自分たちが欲していること、そして人が欲していることが何かを捉えることが大切だ。そして、作り上げ、世に出して、それを広め、人から受け入れられて初めて、jack内外の”Want”が達成できていると考える。
  </p>
  <div class="padding"></div>
  <h2 class="english-shadow" title="prohibition">サークル・団体禁則</h2>
  <p>
    この団体は、飲み会への強制参加およびコールなどの強制飲酒、不当な金銭の要求、不適切な性的関係を目的とした団体ではありません。<br/>
    メンバーの入会および退会はいつでも自由に行えます。<br/>
    未成年の飲酒、喫煙をはじめとする犯罪を助長しません。
  </p>
  <div class="padding"></div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:page_title, "") %>
<div class="page-header" title="contact"></div>
<div class="container">
  <div class="padding"></div>
  <h2 class="english-shadow" title="contact">ご連絡</h2>
  <p>何かご不明な点や、質問したいことがございましたら、次の連絡先からお気軽にご連絡ください。</p>
  <table class="table table-2col">
    <tr>
      <th>フォーム</th>
      <td><%= link_to "<span>Google Form</span>".html_safe, "https://docs.google.com/forms/d/e/1FAIpQLSdkvLbyvnp6rSOxCweb_tW3CPCF8rG-s6yJ8hV6QmHVp9mNxA/viewform?embedded=true", target: '_blank' %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= link_to "<span>jackapp.tmy@gmail.com</span>".html_safe, "mailto:jackapp.tmy@gmail.com" %></td>
    </tr>
    <tr>
      <th>twitter</th>
      <td><a href="https://twitter.com/jackapp_tmy" target="_blank"><span>https://twitter.com/jackapp_tmy</span></a></td>
    </tr>
  </table>
  <div class="hr-padding"></div>
</div>

app/views/static_pages/index.html.erb
<% provide(:page_title, "") %>
<div class="header-back"></div>
<div class="container">
  <div class="padding"></div>
  <div class="row">
    <div class="col-lg-6">
      <h1 class="motto">やりたいことを<br/>やれるようになって、<br/>やる。</h1>
    </div>
    <div class="col-lg-6">
      <p>
        jackは名古屋大学を中心とした、アプリを製作するサークル・団体です。<br/>
        主にAndroidアプリ、iPhoneアプリ、webサービス、パソコン用ソフトなどを開発しています。<br/>
      </p>
      <p>
        やりたいことを「やりたい」だけでとどめず、<br/>
        ITを通じて実現することで、メンバーの成長の機会を提供しています。
      </p>
      <p>
        ワクワクするようなアプリやサービスを生み出したい、素敵なデザインを描いてみたい、あっと驚くような企画を立てたい。
      </p>
      <p>
        jackはいつだって、そんな「やりたい」を歓迎します!
      </p>
    </div>
  </div>
</div>
<div class="container">
  <div class="hr-padding"></div>
  <div class="row">
    <div class="col-md-4 offset-md-4"><%= link_to "2020年 新歓&メンバー募集", welcome_path, class:'button' %></div>
    <!--<div class="col-md-4"><!%= link_to "名大祭2018", meidaisai_path, class:'button' %></div>//-->
  </div>
</div>

app/views/static_pages/meidaisai.html.erb
<% provide(:page_title, "名大祭") %>
<div class="page-header" title="Nagoya Univ Fes 2018"></div>
<div class="container">
  <div class="padding"></div>
  <h2 class="english-shadow" title="Nagoya University Festival">アプリ展示・体験会</h2>
  <p>名大祭2018では、<b>6月9日、10日</b>にて<b>名古屋大学 全学教育棟C21</b>にてアプリの展示・体験会を行います！</p>
  <h2 class="english-shadow">Coming Soon</h2>
  <div class="padding"></div>
</div>

app/views/static_pages/welcome.html.erb
<% provide(:page_title, "新歓 メンバー募集") %>
<div class="page-header" title="welcome"></div>
<div class="container">
  <div class="padding"></div>
  <h2 class="english-shadow" title="member wanted">新歓参加者募集</h2>
  <p>
    jackはパソコンを使ってwebサービスやアプリなどを作っているサークルです！<br/>
    作ってみたいけど全くやり方が分からない人やパソコンを使ったことがない人でも大歓迎！<br/>
    パソコンを使ったものづくりに興味がある方や、自分のアイデアを形にしてみたいという人はまずは新歓でお待ちしております！<br/>
  </p>
  <div class="padding"></div>
  <h3 class="english-shadow" title="contents">新歓内容</h3>
  <p>
    新歓では先輩たちに教わりながら実際にアプリを開発し、jackの活動を体験してもらいます。<br/>
    実際に書いてそれが動いたときに得られる感動、達成感を一緒に味わいましょう！<br/>
  </p>
  <div class="padding"></div>
  <h3 class="english-shadow" title="date&time">新歓日程</h3>
  <table class="table">
    <tr>
      <th>日程</th>
    </tr>
    <tr>
      <td>5月2日(土)  14:00 ~ 16:00 Webサイトを作ろう（チャットBot）</td>
    </tr>
    <tr>
      <td>5月3日(水)  14:00 ~ 16:00 ゲームを作ろう（マリオ風ゲーム）</td>
    </tr>
  </table>
  <div class="padding"></div>
  <h3 class="english-shadow" title="items">持ち物</h3>
  <h5>Zoom（アプリ）の利用できる端末</h5>
  <p>事前にZoomを端末にインストールしていただけますようお願いします。</p>
  <h5>パソコン</h5>
  <p>windows、mac、linuxいずれでも大丈夫です。</p>
  <div class="padding"></div>
  <h3 class="english-shadow" title="place">場所</h3>
    <p>
      コロナの影響を受け対面で新歓を行うことができません！<br/>
      オンライン会議ツールZoomを利用します。<br/>
      Zoomのリンクは直接メールでお送りします。<br/>
    </p>
  <div class="padding"></div>
  <h3 class="english-shadow" title="remarks">注意事項</h3>
  <h5>jackへの加入について</h5>
  <p>
    「新歓に参加したからjackに入らなくてはいけない」ということはありません。<br/>
    今年度にjackに加入する新入生の顔合わせは別日にありますので、 新歓にはお気軽に参加ください。<br/>
  </p>
  <div class="padding"></div>
  <h3 class="english-shadow" title="application">申し込み</h3>
  <p>
    以下のフォームから申し込みをよろしくお願いします。<br/>
    連絡はメールのみとなりますので、確実に連絡の取れるメールアドレスを選んでください。
  </p>
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= link_to "申し込みフォーム", "https://forms.gle/Fx2UYTPBrg5q4yjKA", class:'button', target: '_blank' %></div>
  </div>
  <div class="hr-padding"></div>
</div>