config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'welcome', to: 'static_pages#welcome'
  get 'meidaisai', to: 'static_pages#meidaisai'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :members
  resources :skills
  resources :sns_links
  resources :products
  resources :product_links
  resources :member_products
  resources :entries
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :member
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  before_save { email.downcase! }

  has_many :skills, dependent: :destroy
  has_many :sns_links, dependent: :destroy
  has_many :member_products, dependent: :destroy
  has_many :products, through: :member_products
  has_many :entries
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :university, presence: true
  validates :password, presence: true, allow_nil: true

  def grade
    enroll = self.enroll
    today = Date.today
    grade = 0
    loop {
      grade += 1
      enroll = enroll.next_year
      if today<enroll
        break;
      end
    }
    grade -= self.repeat
    if grade < 1 then grade = 1 end
    if  (grade > 2 && university.match(/大学院/)) ||
        (grade > 4 && university.match(/大学/) && !university.match(/医学科/)) ||
        (grade > 6 && university.match(/大学/) && university.match(/医学科/)) ||
        (grade > 2 && university.match(/短期大学/))
      "卒業"
    else
      "#{(grade)}年"
    end
  end
end

app/models/member_product.rb
class MemberProduct < ApplicationRecord
  belongs_to :member
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  serialize :screenshots
  has_many :members, through: :member_products
  has_many :member_products, dependent: :destroy
  has_many :product_links
  accepts_nested_attributes_for :member_products
end

app/models/product_link.rb
class ProductLink < ApplicationRecord
  belongs_to :product
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :member
end

app/models/sns_link.rb
class SnsLink < ApplicationRecord
  belongs_to :member
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = current_member.entries.new(entry_params)
    if @entry.save
      redirect_to @entry
    else
      render :new
    end
  end

  def update
    if @entry.update(entry_params)
      redirect_to @entry
    else
      render :edit
    end
  end

  def destroy
    @entry.destroy
    redirect_to entries_url
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
      @author = Member.find_by(id: @entry.member_id)
    end

    def entry_params
      params.require(:entry).permit(:name, :body)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :genre, :place, :describe, :start_at, :end_at)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :require_auth, only: [:edit, :update, :destroy]
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  def new
    @member = Member.new
  end
  def create
    @member = Member.new(member_param)
    if @member.save
      login @member
      redirect_to members_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @member.update_attributes(member_param)
      redirect_to member_path(@member)
    else
      render :edit
    end
  end
  def index
    @members = Member.where(leader: false)
    @leaders = Member.where(leader: true)
  end

  def show
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end
  def member_param
    params.require(:member).permit(:name, :email, :university, :password, :password_confirmation, :enroll, :profile, :repeat)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :require_login
  before_action :set_skill, only: [:edit, :update, :destroy]
  def new
    @skill = Skill.new
  end

  def create
    if current_member.skills.create(skill_param)
      redirect_to member_path(current_member.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @skill.update_attributes(skill_param)
      redirect_to member_path(current_member.id)
    else
      render :new
    end
  end

  def destroy
    @skill.destroy
    redirect_to member_path(current_member.id)
  end

  private
  def set_skill
    @skill = Skill.find_by(id: params[:id])
  end
  def skill_param
    params.require(:skill).permit(:name, :start_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    if page_title.empty?
      "jack - アプリ製作団体"
    else
      "#{page_title} | jack - アプリ製作団体"
    end
  end
  def distance_of_time_in_words(from_time, to_time)
    from_time = from_time.to_date if from_time.respond_to?(:to_date)
    to_time = to_time.to_date if to_time.respond_to?(:to_date)
    years = 0
    months = 0
    loop {
      from = from_time + years.year + months.month
      if    (to_time - (from + 1.year))  >= 0 then years  += 1
      elsif (to_time - (from + 1.month)) >= 0 then months += 1
      else break
      end
    }
    distance = ''
    distance += "#{years}年" if years != 0
    distance += "#{months}ヶ月"
    distance
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def gravatar_for(user, options = {size: 100, class:''})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: options[:class])
  end
end

app/helpers/product_links_helper.rb
module ProductLinksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(member)
    session[:member_id] = member.id
  end

  def login?
    !!current_member
  end

  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end

  def member_auth?(member_id)
    login? && current_member.id.to_i == member_id.to_i
  end

  def logout
    session.delete(:member_id)
    @current_member = nil
  end

  def require_login
    until login?
      redirect_to root_path and return
    end
  end
  def require_auth
    until member_auth?(params[:id])
      redirect_to root_path and return
    end
  end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/sns_links_helper.rb
module SnsLinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <lable>タイトル</lable>
    <%= form.text_field :name, id: :entry_name, class:'form-control' %>
  </div>

  <div class="field">
    <lable>本文(htmlが使えます)(改行は自動的に&ltbr&gtタグに変換されます)</lable>
    <%= form.text_area :body, id: :entry_body, rows: '20', class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% provide(:page_title, "記事を編集") %>
<div class="page-header" title="edit blog"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form', entry: @entry %>
</div>

app/views/entries/index.html.erb
<% provide(:page_title, "ブログ") %>
<div class="page-header" title="blog"></div>
<div class="container">
  <div class="padding"></div>
  <%= link_to '新しい記事を投稿する', new_entry_path, class: 'button' if login? %>
  <% @entries.order("created_at DESC").each do |entry| author = Member.find_by(id: entry.member_id) %>
      <h3 class="english-shadow"><%= link_to "<span>#{entry.name}</span>".html_safe, entry %></h3>
      <p align="right"><%= entry.created_at.strftime('%Y年%m月%d日')%> <%= link_to "<span style='padding: 0 1em'>#{author.name}</span>#{gravatar_for author, size: 32}".html_safe, member_path(author.id) %></p>
      <p><%= simple_format(entry.body.truncate(300)) %><%= link_to "<span>続きはこちら</span>".html_safe, entry %></p>
      <% if login? %>
      <div class="row">
        <div class="col-sm-6"><%= link_to '記事を編集する', edit_entry_path(entry), class: 'button' %></div>
        <div class="col-sm-6"><%= link_to '記事を削除する', entry, method: :delete, class: 'button', data: { confirm: '消したら復元できません。よろしいですか？' } %></div>
      </div>
      <% end %>

      <div class="padding"></div>
  <% end %>
  <%= link_to '新しい記事を投稿する', new_entry_path, class: 'button' if login? %>

</div>

app/views/entries/new.html.erb
<% provide(:page_title, "記事を追加") %>
<div class="page-header" title="add blog"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form', entry: @entry %>
</div>

app/views/entries/show.html.erb
<% provide(:page_title, "#{@entry.name} | ブログ") %>
<div class="page-header" title="<%= @entry.name %>"></div>
<div class="container">
  <p align="right">
    <%= @entry.updated_at.strftime('%Y年%m月%d日')%> <%= link_to "<span style='padding: 0 1em'>#{@author.name}</span>#{gravatar_for @author, size: 32}".html_safe, member_path(@author.id) %>
  </p>
  <p>
    <%= simple_format(@entry.body) %>
  </p>
  <% if login? %>
      <div class="row">
        <div class="col-sm-6"><%= link_to '記事を編集する', edit_entry_path(@entry), class: 'button' %></div>
        <div class="col-sm-6"><%= link_to '記事を削除する', @entry, method: :delete, class: 'button', data: { confirm: '消したら復元できません。よろしいですか？' } %></div>
      </div>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    <div class="field">
      <lable>タイトル</lable>
      <%= f.text_field :name, class:'form-control' %>
    </div>

    <div class="field">
      <lable>ジャンル</lable>
      <%= f.text_field :genre, class:'form-control' %>
    </div>

    <div class="field">
      <lable>場所</lable>
      <%= f.text_field :place, class:'form-control' %>
    </div>

    <div class="field">
      <lable>詳細</lable>
      <%= f.text_area :describe, class:'form-control' %>
    </div>

    <div class="field">
      <lable>開始日時</lable><br/>
      <%= f.datetime_select :start_at, class:'form-control' %>
    </div>

    <div class="field">
      <lable>終了日時</lable><br/>
      <%= f.datetime_select :end_at, class:'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/events/edit.html.erb
<% provide(:page_title, "イベントを編集") %>
<div class="page-header" title="edit event"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<% provide(:page_title, "イベント・実績") %>
<div class="page-header" title="events/results"></div>
<div class="container">
  <div class="padding"></div>
  <h3 class="english-shadow" title="events">イベント</h3>
  <p>新歓は、<%= link_to "<span>新歓&メンバー募集</span>".html_safe, welcome_path %>で取り扱っています。</p>
  <%= link_to "イベントを追加する", new_event_path, class: "button" if login? %>
  <table class="table">
    <% @events.order("start_at DESC").each do |event| %>
        <tr>
          <td><%= event.start_at.strftime('%Y年%-m月%-d日') %></td>
          <td>
            <%= event.name %>
            <%= link_to "<span>編集</span>".html_safe, edit_event_path(event) if login? %>
            <%= link_to "<span>削除</span>".html_safe, event, method: :delete if login? %>
          </td>
        </tr>
        <% if !event.describe.nil? && !event.describe.blank? %>
          <tr>
            <td colspan="2" style="padding-left: 2em;"><%= event.describe %></td>
          </tr>
        <% end %>
    <% end %>
  </table>
  <div class="padding"></div>
</div>

app/views/events/new.html.erb
<% provide(:page_title, "イベントを追加") %>
<div class="page-header" title="add event"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form' %>
</div>

app/views/members/_form.html.erb
<%= form_for @member do |f| %>
    <div class="form-group">
      <label>メンバー名</label>
      <%= f.text_field :name, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>メールアドレス</label>
      <%= f.email_field :email, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>所属大学・学部・学科または所属大学院・研究科</label>
      <%= f.text_field :university, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>ログインパスワード</label>
      <%= f.password_field :password, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>ログインパスワード再確認</label>
      <%= f.password_field :password_confirmation, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>入学年月日(日付は 4月1日に設定してください。)</label><br/>
      <%= f.date_select :enroll, class:'form-control' %>
    </div>


    <div class="form-group">
      <label>留年数</label>
      <%= f.number_field :repeat, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>プロフィール</label>
      <%= f.text_area :profile, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit %>
    </div>
<% end %>

app/views/members/edit.html.erb
<% provide(:page_title, "#{@member.name}の編集") %>
<div class="page-header" title="edit <%= @member.name %>"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form' %>
  <div class="gravatar_edit">
    <%= gravatar_for @member %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
</div>

app/views/members/index.html.erb
<% provide(:page_title, "メンバー") %>
<div class="page-header" title="members"></div>
<div class="container">
  <div class="padding"></div>
  <h2 class="english-shadow" title="Leader">代表</h2>
  <div class="row">
    <% @leaders.each do |leader| %>
        <div class="col-md-2 col-sm-3 col-6">
          <div class="member-item">
            <%= link_to "#{gravatar_for leader}<br/><span>#{leader.name}</span>".html_safe, member_path(leader) %>
            </a>
          </div>
        </div>
    <% end %>
  </div>
  <h2 class="english-shadow" title="Members">メンバー</h2>
  <div class="row">
    <% @members.each do |member| %>
        <div class="col-md-2 col-sm-3 col-6">
          <div class="member-item">
            <%= link_to "#{gravatar_for member}<br/><span>#{member.name}</span>".html_safe, member_path(member) %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/members/new.html.erb
<% provide(:page_title, "新規メンバー") %>
<div class="page-header" title="sign up"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form' %>
</div>

app/views/members/show.html.erb
<% provide(:page_title, "#{@member.name} | メンバー") %>
<div class="page-header" title="<%= @member.name %>" style="color: #ffffff">
  <%= gravatar_for @member, size: 100, class:'icon' %>
</div>
<div class="container profile">
  <div class="padding"></div>
  <table class="table table-2col">
    <tr>
      <th>所属</th>
      <td><%= @member.university %><%= @member.grade %></td>
    </tr>
    <tr>
      <th>作品</th>
      <td>
        <% @member.member_products.each do |member_product| %>
            <%= member_product.product.name %><br/>
        <% end %>
        <%= link_to "<span>作品を追加する</span>".html_safe, new_product_path if member_auth?(params[:id]) %>
      </td>
    </tr>
    <tr>
      <th>スキル</th>
      <td>
        <% @member.skills.order(:start_at).each do |skill| %>
            <%= skill.name %><span class="badge"><%= distance_of_time_in_words(skill.start_at, Date.today)%></span>
            <%= link_to "<span>編集</span>".html_safe, edit_skill_path(skill) if member_auth?(params[:id]) %>
            <%= link_to "<span>削除</span>".html_safe, skill_path(skill), method: :delete if member_auth?(params[:id]) %>
            <br/>
        <% end %>
        <%= link_to "<span>スキルを追加する</span>".html_safe, new_skill_path if member_auth?(params[:id]) %>
      </td>
    </tr>
    <tr>
      <th>プロフィール</th>
      <td><%= simple_format(@member.profile) %></td>
    </tr>
    <tr>
      <th>連絡先</th>
      <td>
        email: <a href="mailto:<%= @member.email %>"><span><%= @member.email %></span></a><br/>
        <% @member.sns_links.each do |sns_link| %>
            <%= sns_link.name %>: <a href="<%= sns_link.url %>"><span><%= sns_link.url %></span></a>
            <%= link_to "<span>編集</span>".html_safe, edit_sns_link_path(sns_link) if member_auth?(params[:id]) %>
            <%= link_to "<span>削除</span>".html_safe, sns_link_path(sns_link), method: :delete if member_auth?(params[:id]) %><br/>
        <% end %>
        <%= link_to "<span>SNSを追加する</span>".html_safe, new_sns_link_path if member_auth?(params[:id]) %>
      </td>
    </tr>
  </table>
  <% if member_auth?(params[:id]) %>
      <div class="padding"></div>
      <div class="row">
        <div class="col-md-4"><%= link_to "プロフィールを編集する", edit_member_path(params[:id]), class:'button' %></div>
      </div>
  <% end %>
  <div class="hr-padding"></div>
</div>

app/views/skills/edit.html.erb
<% provide(:page_title, "スキル編集") %>
<div class="page-header" title="edit skill"></div>
<div class="container">
  <div class="padding"></div>
  <%= form_for @skill do |f| %>
      <div class="form-group">
        <label>スキル・言語名(HTML, Python, Adobe Illustrator, Unityなど)</label>
        <%= f.text_field :name, class:'form-control' %>
      </div>

      <div class="form-group">
        <label>やり始めた日</label>
        <%= f.date_select :start_at, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/skills/new.html.erb
<% provide(:page_title, "スキル追加") %>
<div class="page-header" title="add skill"></div>
<div class="container">
  <div class="padding"></div>
  <%= form_for @skill do |f| %>
      <div class="form-group">
        <label>スキル・言語名(HTML, Python, Adobe Illustrator, Unityなど)</label>
        <%= f.text_field :name, class:'form-control' %>
      </div>

      <div class="form-group">
        <label>やり始めた日</label>
        <%= f.date_select :start_at, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit %>
      </div>
  <% end %>
</div>