config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'welcome', to: 'static_pages#welcome'
  get 'meidaisai', to: 'static_pages#meidaisai'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :members
  resources :skills
  resources :sns_links
  resources :products
  resources :product_links
  resources :member_products
  resources :entries
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :member
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  before_save { email.downcase! }

  has_many :skills, dependent: :destroy
  has_many :sns_links, dependent: :destroy
  has_many :member_products, dependent: :destroy
  has_many :products, through: :member_products
  has_many :entries
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :university, presence: true
  validates :password, presence: true, allow_nil: true

  def grade
    enroll = self.enroll
    today = Date.today
    grade = 0
    loop {
      grade += 1
      enroll = enroll.next_year
      if today<enroll
        break;
      end
    }
    grade -= self.repeat
    if grade < 1 then grade = 1 end
    if  (grade > 2 && university.match(/大学院/)) ||
        (grade > 4 && university.match(/大学/) && !university.match(/医学科/)) ||
        (grade > 6 && university.match(/大学/) && university.match(/医学科/)) ||
        (grade > 2 && university.match(/短期大学/))
      "卒業"
    else
      "#{(grade)}年"
    end
  end
end

app/models/member_product.rb
class MemberProduct < ApplicationRecord
  belongs_to :member
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  serialize :screenshots
  has_many :members, through: :member_products
  has_many :member_products, dependent: :destroy
  has_many :product_links
  accepts_nested_attributes_for :member_products
end

app/models/product_link.rb
class ProductLink < ApplicationRecord
  belongs_to :product
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :member
end

app/models/sns_link.rb
class SnsLink < ApplicationRecord
  belongs_to :member
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = current_member.entries.new(entry_params)
    if @entry.save
      redirect_to @entry
    else
      render :new
    end
  end

  def update
    if @entry.update(entry_params)
      redirect_to @entry
    else
      render :edit
    end
  end

  def destroy
    @entry.destroy
    redirect_to entries_url
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
      @author = Member.find_by(id: @entry.member_id)
    end

    def entry_params
      params.require(:entry).permit(:name, :body)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :genre, :place, :describe, :start_at, :end_at)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  def index
    @products = Product.all
  end

  def new
    @product = Product.new()
  end

  def create
    @product = Product.new(product_param)
    if @product.save
      MemberProduct.create(member: current_member, product: @product)
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_param)
      redirect_to products_path
    else
      render :new
    end

  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
    def product_param
      p = params.require(:product).permit(:name, :genre, :price, :start_at, :end_at, :slogan, :describe, :icon_url, :movie_url)
      md = p[:movie_url].match(/https:\/\/youtu.be\/(.+)/)
      if !md.nil? then p[:movie_url] = "https://www.youtube.com/embed/#{md[1]}" end
      p
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :require_login
  before_action :set_skill, only: [:edit, :update, :destroy]
  def new
    @skill = Skill.new
  end

  def create
    if current_member.skills.create(skill_param)
      redirect_to member_path(current_member.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @skill.update_attributes(skill_param)
      redirect_to member_path(current_member.id)
    else
      render :new
    end
  end

  def destroy
    @skill.destroy
    redirect_to member_path(current_member.id)
  end

  private
  def set_skill
    @skill = Skill.find_by(id: params[:id])
  end
  def skill_param
    params.require(:skill).permit(:name, :start_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    if page_title.empty?
      "jack - アプリ製作団体"
    else
      "#{page_title} | jack - アプリ製作団体"
    end
  end
  def distance_of_time_in_words(from_time, to_time)
    from_time = from_time.to_date if from_time.respond_to?(:to_date)
    to_time = to_time.to_date if to_time.respond_to?(:to_date)
    years = 0
    months = 0
    loop {
      from = from_time + years.year + months.month
      if    (to_time - (from + 1.year))  >= 0 then years  += 1
      elsif (to_time - (from + 1.month)) >= 0 then months += 1
      else break
      end
    }
    distance = ''
    distance += "#{years}年" if years != 0
    distance += "#{months}ヶ月"
    distance
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def gravatar_for(user, options = {size: 100, class:''})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: options[:class])
  end
end

app/helpers/product_links_helper.rb
module ProductLinksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(member)
    session[:member_id] = member.id
  end

  def login?
    !!current_member
  end

  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end

  def member_auth?(member_id)
    login? && current_member.id.to_i == member_id.to_i
  end

  def logout
    session.delete(:member_id)
    @current_member = nil
  end

  def require_login
    until login?
      redirect_to root_path and return
    end
  end
  def require_auth
    until member_auth?(params[:id])
      redirect_to root_path and return
    end
  end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/sns_links_helper.rb
module SnsLinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <div class="form-group">
      <label>作品名</label>
      <%= f.text_field :name, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>ジャンル</label>
      <%= f.text_field :genre, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>価格(円)</label>
      <%= f.number_field :price, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>開発開始日</label><br/>
      <%= f.date_select :start_at, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>開発終了日</label><br/>
      <%= f.date_select :end_at, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>キャッチコピー</label>
      <%= f.text_field :slogan, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>詳細</label>
      <%= f.text_area :describe, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>アイコンURL</label>
      <%= f.text_field :icon_url, class:'form-control' %>
    </div>

    <div class="form-group">
      <label>動画URL</label>
      <%= f.text_field :movie_url, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit %>
    </div>
<% end %>

app/views/products/edit.html.erb
<% provide(:page_title, "作品編集") %>
<div class="page-header" title="edit product"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form' %>
  <div class="padding"></div>
</div>

app/views/products/index.html.erb
<% provide(:page_title, "作品") %>
<div class="page-header" title="products"></div>
<div class="container">
  <% @products.each do |product| %>
      <div class="padding"></div>
      <div class="product">
        <div class="row">
          <div class="col-4">
            <%= image_tag product.icon_url, class: "logo" if !product.icon_url.nil? && !product.icon_url.blank? %>
            <div class="big-page">
              <% product.product_links.each do |link| %>
                  <a href="<%= link.url %>" class="button"><%= link.name %></a>
                  <%= link_to "<span>#{link.name}編集</span>".html_safe, edit_product_link_path(link) if login? %>
                  <%= link_to "<span>#{link.name}削除</span>".html_safe, product_link_path(link), method: :delete if login? %>
              <% end %>
              <%= link_to "リンク追加", new_product_link_path(product_id: product.id), class:'button' if login? %>
            </div>
          </div>
          <div class="col-8">
            <h2 class="title english-shadow"><%= product.name %></h2>
            <div class="genre">
              <table class="table table-sm">
                <tr>
                  <th>ジャンル</th>
                  <td><%= product.genre %></td>
                </tr>
                <tr>
                  <th>価格</th>
                  <td><%= product.price %>円</td>
                </tr>
                <tr>
                  <th>メンバー</th>
                  <td>
                    <ul>
                      <% product.member_products.each do |member_product| member = member_product.member %>
                        <li><%= link_to "<span>#{member.name}</span>".html_safe, member %><%= link_to "<span>削除</span>".html_safe, member_product_path(member_product.id), method: :delete if login? %></li>
                      <% end %>
                    </ul>
                    <%= link_to "<span>追加</span>".html_safe, new_member_product_path(product_id: product.id) if login? %>
                  </td>
                </tr>
              </table>
            </div>
            <h5 class="slogan big-page"><%= product.slogan %></h5>
            <p class="describe big-page"><%= product.describe %></p>
          </div>
        </div>
        <h5 class="slogan small-page"><%= product.slogan %></h5>
        <p class="small-page">
          <%= product.describe %>
        </p>
        <div class="row small-page">
          <% product.product_links.each do |link| %>
              <div class="col-sm-6">
                <a href="<%= link.url %>" class="button"><%= link.name %></a><br/>
                <%= link_to "<span>#{link.name}編集</span>".html_safe, edit_product_link_path(link) if login? %>
                <%= link_to "<span>#{link.name}削除</span>".html_safe, product_link_path(link), method: :delete if login? %>
              </div>
          <% end %>
          <% if login? %>
              <div class="col-sm-6"><%= link_to "リンク追加", new_product_link_path(product_id: product.id), class:'button' %></div>
          <% end %>
        </div>
        <div class="row">
          <% if !product.movie_url.nil? and !product.movie_url.blank? %>
              <div class="col-sm-6 col-12">
                <div class="movie-wrapper"><iframe class="movie" src="<%= product.movie_url %>" frameborder="0" allow="encrypted-media" allowfullscreen></iframe></div>
              </div>
          <% end %>

          <% if product.screenshots %>
              <% product.screenshots.each do |screenshot| %>
                  <div class="col-sm-2 col-4">
                    <%= image_tag screenshot[:url], class: "screen-shot" %>
                  </div>
              <% end %>
        <% end %>
        </div>
      </div>
      <% if login? %>
          <div class="row">
            <div class="col-6"><%= link_to "#{product.name}を編集する", edit_product_path(product.id), class:'button' %></div>
            <div class="col-6"><%= link_to "#{product.name}を削除する", product_path(product.id),method: :delete, class:'button' %></div>
          </div>
      <% end %>
      <div class="hr-padding"></div>
  <% end %>
</div>

app/views/products/new.html.erb
<% provide(:page_title, "作品登録") %>
<div class="page-header" title="add product"></div>
<div class="container">
  <div class="padding"></div>
  <%= render 'form' %>
  <div class="padding"></div>
</div>