config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'welcome', to: 'static_pages#welcome'
  get 'meidaisai', to: 'static_pages#meidaisai'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :members
  resources :skills
  resources :sns_links
  resources :products
  resources :product_links
  resources :member_products
  resources :entries
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :member
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  before_save { email.downcase! }

  has_many :skills, dependent: :destroy
  has_many :sns_links, dependent: :destroy
  has_many :member_products, dependent: :destroy
  has_many :products, through: :member_products
  has_many :entries
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :university, presence: true
  validates :password, presence: true, allow_nil: true

  def grade
    enroll = self.enroll
    today = Date.today
    grade = 0
    loop {
      grade += 1
      enroll = enroll.next_year
      if today<enroll
        break;
      end
    }
    grade -= self.repeat
    if grade < 1 then grade = 1 end
    if  (grade > 2 && university.match(/大学院/)) ||
        (grade > 4 && university.match(/大学/) && !university.match(/医学科/)) ||
        (grade > 6 && university.match(/大学/) && university.match(/医学科/)) ||
        (grade > 2 && university.match(/短期大学/))
      "卒業"
    else
      "#{(grade)}年"
    end
  end
end

app/models/member_product.rb
class MemberProduct < ApplicationRecord
  belongs_to :member
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  serialize :screenshots
  has_many :members, through: :member_products
  has_many :member_products, dependent: :destroy
  has_many :product_links
  accepts_nested_attributes_for :member_products
end

app/models/product_link.rb
class ProductLink < ApplicationRecord
  belongs_to :product
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :member
end

app/models/sns_link.rb
class SnsLink < ApplicationRecord
  belongs_to :member
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :genre, :place, :describe, :start_at, :end_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    if page_title.empty?
      "jack - アプリ製作団体"
    else
      "#{page_title} | jack - アプリ製作団体"
    end
  end
  def distance_of_time_in_words(from_time, to_time)
    from_time = from_time.to_date if from_time.respond_to?(:to_date)
    to_time = to_time.to_date if to_time.respond_to?(:to_date)
    years = 0
    months = 0
    loop {
      from = from_time + years.year + months.month
      if    (to_time - (from + 1.year))  >= 0 then years  += 1
      elsif (to_time - (from + 1.month)) >= 0 then months += 1
      else break
      end
    }
    distance = ''
    distance += "#{years}年" if years != 0
    distance += "#{months}ヶ月"
    distance
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def gravatar_for(user, options = {size: 100, class:''})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: options[:class])
  end
end

app/helpers/product_links_helper.rb
module ProductLinksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(member)
    session[:member_id] = member.id
  end

  def login?
    !!current_member
  end

  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end

  def member_auth?(member_id)
    login? && current_member.id.to_i == member_id.to_i
  end

  def logout
    session.delete(:member_id)
    @current_member = nil
  end

  def require_login
    until login?
      redirect_to root_path and return
    end
  end
  def require_auth
    until member_auth?(params[:id])
      redirect_to root_path and return
    end
  end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/sns_links_helper.rb
module SnsLinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/barba.js/1.0.0/barba.min.js" type="text/javascript"></script>
  </head>

  <body>
  <header class="header">
    <%= link_to image_tag('jack_white.svg'), root_path, class:'logo' %>
    <ul class="list-inline">
      <li class="list-inline-item"><%= link_to "jackとは", about_path %></li>
      <li class="list-inline-item"><%= link_to "作品", products_path %></li>
      <li class="list-inline-item"><%= link_to "2020年新歓", welcome_path %></li>
      <li class="list-inline-item"><%= link_to "イベント・実績", events_path %></li>
      <!--<li class="list-inline-item"><!%= link_to "ブログ", entries_path %></li>//-->
      <!--<li class="list-inline-item"><!%= link_to "メンバー", members_path %></li>//-->
      <li class="list-inline-item"><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </header>
  <div id="barba-wrapper" aria-live="polite">
    <div class="barba-container">
      <%= yield %>
    </div>
  </div>
  <div class="container">
    <hr>
    <div class="copyright">2016-<%= Date.today.year %> &copy; jack<%= login? ? " logged in as #{current_member.name} #{link_to "logout", logout_path, method: :delete}".html_safe: "" %></div>
    <div><%= debug(params) if Rails.env.development? %></div>
  </div>
  </body>
</html>